### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by arsgsg1** [classvar/classvar-user-backend#8]
- [x] 컨트롤러 PostMapping 및 검증 로직 작성
- [ ] Standard Response Class 정의
- [ ] illegalArgumentException 예외를 감싸 커스텀 예외로 바꾸는 작업
- [ ] 컨트롤러 GetMapping 로직 작성
- [ ] 통합 테스트 코드 작성

**Comment by arsgsg1** [comment]
Standard Response Class 정의 : https://github.com/classvar/classvar-user-backend/commit/c5d8f8d0c309e728931c167b8bfa54ca2e0279cc
